# Chap 3 回帰分析と最小二乗法


![](https://m.media-amazon.com/images/I/51+dt08QnxL._SY346_.jpg)

# 3.1 回帰分析 (p49)

- 重回帰モデル

$$
\begin{aligned}
\mathbf{x} &= \begin{bmatrix} x_1 \\ \vdots \\ x_{M} \end{bmatrix} \in \mathbb{R}^M \ (入力変数)  , \ \
\mathbf{\beta} = \begin{bmatrix} \beta_1 \\ \vdots \\ \beta_{M} \end{bmatrix} \in \mathbb{R}^M \ \ (係数)\\
y &= \beta_1 x_1 + \dots + \beta_M x_M + \beta_0 +  \epsilon \ \ & (3.2) \\
&= \mathbf{\beta}^T \mathbf{x} + \beta_0 + \epsilon \ \  & (3.3) \\
\end{aligned}
$$

# 3.2 最小二乗法

p53 (3.16)


- 積和行列$X^TX$が正則であれば、逆行列が存在するので、回帰係数ベクトル$\beta$は、解析的に求めることができる
- この解を最小二乗解と呼びます

$$
\begin{aligned}
X &= \begin{bmatrix} x_{1,1} & \dots & x_{1,M} \\
\vdots & \ddots & \vdots \\
x_{N,1} & \dots & x_{N,M}
\end{bmatrix} 
= \begin{bmatrix} - \mathbf{x}_1 - \\ \vdots \\ - \mathbf{x}_N - \end{bmatrix} & (3.4) \\
\mathbf{\beta} &= \begin{bmatrix} \beta_1 \\ \vdots \\ \beta_M \end{bmatrix}  \\
\mathbf{y} &= \begin{bmatrix} y_1 \\ \vdots \\ y_N \end{bmatrix} & (3.5) \\
X\beta &\simeq y \ \  (なるべく等しくなるような\betaを決めたい)\\
X^T X \hat{\beta} &= X^T y \\
\hat{\beta} &= (X^T X)^{-1} X^T y & (3.16)
\end{aligned}
$$

# 3.4 最小二乗法の幾何学的意味
    - $Im X$は行列$X$の列ベクトルの線形結合

$$
\begin{aligned}
\hat{y} &= X \hat{\beta} \\
\hat{y} &= X (X^T X)^{-1} X^T y & (3.22) \\
\hat{y} &= P y \ \ \ \ (\because P= X (X^T X)^{-1} X^T \ \ 射影行列 )\\
\end{aligned}
$$

<div style="text-align:center">
<img src="img/fig3.3.PNG" width="40%" >
</div>

<hr>

p56 (3.23)

- 行列 $P$が射影行列の証明

$$
\begin{aligned}
P &= X (X^T X)^{-1} X^T \ \\ \\
P^2 &= PP & (3.23) \\
&= (X (X^T X)^{-1} X^T) \ (X (X^T X)^{-1} X^T) & (3.24)\\
&= X \ (X^T X)^{-1} (X^T X ) \ (X^T X)^{-1} \ X^T & (3.25) \\
&= X  (X^T X)^{-1}  X^T \\
&= P & (3.26)\\
\end{aligned}
$$

## プログラム3.2 最小二乗法の数値例 (p54)

In [1]:
import numpy as np
from linear_regression import least_squares , ls_est

np.set_printoptions(formatter={'float':'{: .4f}'.format})

# データを定義します
X = np.array([[0.01, 0.50, -0.12],
			[0.97, -0.63, 0.02],
			[0.41, 1.15, -1.17],
			[-1.38, -1.02, 1.27]])

y = np.array([[0.25], [0.08], [1.03], [-1.37]])
x = np.array([1, 0.7, -0.2])


# 回帰係数を求めます．
beta = least_squares(X, y)
print(beta)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
# 未知サンプルから出力を予測します
y_hat = ls_est(x, beta)
print(y_hat)
# [0.7241999]

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[ 0.7242]


## *numpy from scratch (TODO)

## *sklearn.linear_model.LinearRegression

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
lr = LinearRegression(fit_intercept=True)

In [4]:
lr.fit(X,y)

LinearRegression()

In [5]:
lr.coef_, lr.intercept_

(array([[ 0.3636,  0.4164, -0.3466]]), array([-0.0034]))

# 3.7 多重共線性の問題 (p62)

- 悪条件 (ill-conditioned)
    - 本来はランクが落ちているはずの行列が、測定ノイズなどによってフルランクとなり、逆行列が大きくばらつく状況
- 行列が悪条件であるかは、__条件数__ という尺度で判定できる


$A$の条件数$\kappa(A)$ 
- $A$の最大特異値，最小特異値を$\sigma_{max}, \sigma_{min}$ として

$$
\kappa(A) = \frac{\sigma_{max}}{\sigma_{min}}
$$


<hr>

条件数は、`numpy.linalg.cond`で確認できる

## プログラム3.3 多重共線性がないデータの場合 (p65)

In [6]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[0.01, 0.50, -0.12],
                [0.97, -0.63, 0.02],
                [0.41, 1.15, -1.17],
                [-1.38, -1.02, 1.27]])
X2 = np.array( [[-0.01, 0.52, -0.12],
                [0.96, -0.64, 0.03],
                [0.43, 1.14, -1.17],
                [-1.38, -1.01, 1.27]])

y = np.array ([[0.25], [0.08], [1.03], [-1.37]])


# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
beta2 = least_squares(X2, y)
print(beta2)
# [[ 0.37270979]
# [ 0.41379869]
# [-0.34252764]]

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[[ 0.3727]
 [ 0.4138]
 [-0.3425]]


In [7]:
X1 - X2

array([[ 0.0200, -0.0200,  0.0000],
       [ 0.0100,  0.0100, -0.0100],
       [-0.0200,  0.0100,  0.0000],
       [ 0.0000, -0.0100,  0.0000]])

### 行列の条件数 $\kappa(A)$

In [8]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2)

(135.75293858717927, 133.39346575985206)

## プログラム3.4 多重共線性があるデータの場合 (p67)

In [9]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array([0.4, 1.17, -1.14, -0.42])

# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[0.54496962]
# [0.24094799]
# [1.64044474]]

beta2 = least_squares(X2, y)
print(beta2)
# [[-0.42794288]
# [-2.86298696]
# [-2.2029719 ]]

[[ 0.5450]
 [ 0.2409]
 [ 1.6404]]
[[-0.4279]
 [-2.8630]
 [-2.2030]]


In [10]:
X1 - X2

array([[ 0.0000,  0.0000, -0.0100],
       [ 0.0000,  0.0000,  0.0100],
       [ 0.0100,  0.0000,  0.0000],
       [-0.0100,  0.0000,  0.0000]])

### 行列の条件数 $\kappa(A)$

In [11]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2),

(235456.75658580603, 470649.97301951883)

## *条件数 myCond (numpy from scratch)

In [12]:
U, s, VT = np.linalg.svd(X)
U, s, VT

(array([[-0.1371, -0.2290,  0.8271,  0.4946],
        [-0.0466,  0.8634, -0.0664,  0.4979],
        [-0.6028, -0.3618, -0.5016,  0.5041],
        [ 0.7846, -0.2667, -0.2448,  0.5033]]),
 array([ 2.6820,  1.3318,  0.2302]),
 array([[-0.5132, -0.5715,  0.6403],
        [ 0.7921, -0.6026,  0.0971],
        [ 0.3303,  0.5570,  0.7620]]))

In [13]:
def myCond(X):
    U, s, VT = np.linalg.svd(X)
    return s.max()/s.min()

In [14]:
myCond(X1.T@X1)

235456.7565858061

## *sklearn.linear_model.LinearRegression

In [15]:
lr = LinearRegression()
lr.fit(X1, y)
lr.coef_, lr.intercept_

(array([ 0.5325,  0.2005,  1.5906]), 0.00116875115519689)

In [16]:
lr = LinearRegression()
lr.fit(X2, y)
lr.coef_, lr.intercept_

(array([-0.5122, -3.1292, -2.5334]), 0.0037806003603919093)

# 3.8 サンプル数が入力変数の数よりも少ない場合

- 方程式の数より未知数が多いのだから、普通の方程式では解けるはずがない 
    - 無数の解が存在する

$$
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\
x_{21} & x_{22} & x_{23}
\end{bmatrix}
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\end{bmatrix} =
\begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
\end{bmatrix}
$$

- 一方、よく見る最小二乗法の問題では、未知数より方程式の和の方が多い、やはり、普通の方程式の解き方とは違う

$$
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\
x_{23} & x_{22} & x_{23} \\
x_{31} & x_{32} & x_{33} \\
x_{41} & x_{42} & x_{43} \\
x_{51} & x_{52} & x_{53} \\
x_{61} & x_{67} & x_{63} \\
x_{71} & x_{72} & x_{73} \\
x_{81} & x_{82} & x_{83} \\
x_{91} & x_{92} & x_{93}
\end{bmatrix}
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\end{bmatrix} =
\begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
\end{bmatrix}
$$

# 3.9 擬似逆行列を用いる方法 (TODO)


サンプル数が入力変数の数よりも少ない場合でも、多重共線性が問題となる場合でも、

積和行列$X^TX$の逆行列$(X^T X)^{−1}$と似た働きをする都合のよい行列があれば便利



- 行列$A$に対して、以下のような$A^{+}$ ()
    - $AA^+A = A$
    - $A^+AA^+ = A$
    - $(AA^+)^T = AA^+$
    - $(A^+A)^T = A^+A$


$$
\beta^* = (X^T X)^+ X^T y
$$

## *numpy.linalg.pinv (疑似逆行列)

- 上記の条件を満たすか？

In [17]:
A = np.array([[1, 2],
              [2, 4]])

A_ = np.linalg.pinv(A)
A_, np.linalg.matrix_rank(A)

(array([[ 0.0400,  0.0800],
        [ 0.0800,  0.1600]]),
 1)

In [18]:
# AA^+A = A
A @ A_, A

(array([[ 0.2000,  0.4000],
        [ 0.4000,  0.8000]]),
 array([[1, 2],
        [2, 4]]))

In [19]:
# A^+AA^+ = A
A_ @ A @ A_, A

(array([[ 0.0400,  0.0800],
        [ 0.0800,  0.1600]]),
 array([[1, 2],
        [2, 4]]))

In [20]:
# (AA^+)^T = AA^+

(A @ A_).T, A @ A_

(array([[ 0.2000,  0.4000],
        [ 0.4000,  0.8000]]),
 array([[ 0.2000,  0.4000],
        [ 0.4000,  0.8000]]))

In [21]:
# (A^+A)^T = A^+A
(A_ @ A).T, A_ @ A

(array([[ 0.2000,  0.4000],
        [ 0.4000,  0.8000]]),
 array([[ 0.2000,  0.4000],
        [ 0.4000,  0.8000]]))

# 3.10 主成分回帰 (PCR) (p72)

- 多重共線性の問題は、入力データの変数間の相関に起因する
- 変数間が無相関になるような前処理をすればよい
    - PCAで次元削減して回帰問題を解けばよい

<div style="text-align:center">
<img src="img/fig3.6.PNG" width="40%" >
</div>

- [Principal Component Regression vs Partial Least Squares Regression](https://scikit-learn.org/stable/auto_examples/cross_decomposition/plot_pcr_vs_pls.html)

## プログラム3.5 PCR（linear_regression.py） (p73)

In [22]:
import numpy as np
from linear_regression import least_squares
from pca import pca

def pcr(X, y, R):
    """
    PCR を用いて回帰係数を計算します．ラメータ
    ----------
    X: 入力データ
    y: 出力データ
    R: 主成分の数
    戻り値
    -------
    beta: 回帰係数
    """
    # yをベクトル化します
    y = y.reshape(-1, 1)
    # 主成分分析を行います
    P, T = pca(X)
    # R番目までの主成分得点行列を取り出します
    T = T[:,:R]
    # 最小二乗法により回帰係数を求めます
    beta_R = least_squares(T, y)
    beta = P[:,:R] @ beta_R
    return beta

## *MyPCR (sklearn from scratch)

- PCRはPCAで入力データの次元削減と次元復元(?)によって、多重共線性問題を回避している 
- 次元削減/復元により、情報量の一部を失うが、多重共線性問題は回避している

In [23]:
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

class MyPCR(TransformerMixin, BaseEstimator):
    def __init__(self, n_components):
        self.n_components = n_components
        self.pca = PCA(n_components=n_components)
        self.regression = LinearRegression()
    def fit(self, X, y=None):
        self.pca.fit(X)
        X_reduced = self.pca.transform(X)                  # <= 次元削減
        X_returned = self.pca.inverse_transform(X_reduced) # <= 次元復元
        self.regression.fit(X_returned,y)
        self.coef_ = self.regression.coef_
        self.intercept_ = self.regression.intercept_
        return self
    def predict(self, X):
        X_reduced = self.pca.transform(X)
        X_returned = self.pca.inverse_transform(X_reduced)
        return self.regression.predict(X_returned)

## プログラム3.6 主成分数を2 とした場合 (p74)

In [24]:
# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array ([[0.4], [1.17], [-1.14], [-0.42]])

#主成分数を2に設定します
R = 2
beta1 = pcr(X1, y, R)
print(beta1)
# [[ 0.25849154]
# [-0.68874152]
# [ 0.49387146]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[ 0.25929082]
# [-0.69212429]
# [ 0.49149105]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6921]
 [ 0.4915]]


In [25]:
myPCR = MyPCR(n_components=2)
myPCR.fit(X1, y)
myPCR.coef_, myPCR.intercept_

(array([[ 0.2585, -0.6887,  0.4939]]), array([ 0.0019]))

In [26]:
myPCR = MyPCR(n_components=2)
myPCR.fit(X2, y)
myPCR.coef_, myPCR.intercept_

(array([[ 0.2593, -0.6921,  0.4915]]), array([ 0.0019]))

## プログラム3.7 主成分数を1 とした場合 (p75)

In [27]:
# 主成分数を1 に設定します
R = 1
beta1 = pcr(X1, y, R)
print(beta1)
# [[-0.30313539]
# [-0.32858522]
# [ 0.34217102]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[-0.30335458]
# [-0.32755389]
# [ 0.34127419]]

[[-0.3031]
 [-0.3286]
 [ 0.3422]]
[[-0.3034]
 [-0.3276]
 [ 0.3413]]


In [28]:
myPCR = MyPCR(n_components=1)
myPCR.fit(X1, y)
myPCR.coef_, myPCR.intercept_

(array([[-0.3031, -0.3286,  0.3422]]), array([ 0.0033]))

In [29]:
myPCR = MyPCR(n_components=1)
myPCR.fit(X2, y)
myPCR.coef_, myPCR.intercept_

(array([[-0.3034, -0.3276,  0.3413]]), array([ 0.0033]))

# 3.11 リッジ回帰

## プログラム3.8 リッジ回帰（linear_regression） (p77)

In [30]:
def ridge(X, y, mu=0.1):
    """
    リッジ回帰を用いて回帰係数を計算します. 

    パラメータ
    ----------
    X: 入力データ
    y: 出力データ
    mu: パラメータ(デフォルト: 0.1)

    戻り値
    -------
    beta_ridge: 回帰係数
    """
    # yをベクトル化します
    y = y.reshape(-1, 1)

    # リッジ回帰の回帰係数を求めます
    I = np.eye(X.shape [1])
    beta_ridge = np.linalg.inv(X.T @ X + mu * I)@ X.T @ y
    return beta_ridge

## *sklearn.linear_model.Ridge

In [31]:
from sklearn.linear_model import Ridge

## *MyRidge (numpy from scratch) 

- 式 (3.91)を愚直に行列で計算する

$$
\beta_{ridge} = (X^T X + \mu I)^{-1} X^T y \tag{3.91}
$$

In [32]:
import numpy as np
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.decomposition import PCA

class MyRidge(TransformerMixin, BaseEstimator):
    def __init__(self, mu=0.1):
        self.mu = mu
        self.beta = None
        
    def fit(self, X, y):
        m, n = X.shape
        self.beta = np.linalg.inv(X.T @ X + mu*np.eye(n)) @ X.T @ y
        return self
    def predict(self, X):
        return X @self.beta

## プログラム3.9 リッジ回帰($\mu = 0.1$)の数値例 (p79)

In [33]:
# パラメータを0.1に設定します
mu = 0.1
beta1 = ridge(X1, y, mu)
print(beta1)
# [[ 0.21088992]
# [-0.65139114]
# [ 0.47615414]]
beta2 = ridge(X2, y, mu)
print(beta2)

# [[ 0.21198147]
# [-0.65545325]
# [ 0.47322964]]

[[ 0.2109]
 [-0.6514]
 [ 0.4762]]
[[ 0.2120]
 [-0.6555]
 [ 0.4732]]


In [34]:
skridge = Ridge(alpha=0.1)
skridge.fit(X1, y)
skridge.coef_, skridge.intercept_

(array([[ 0.2109, -0.6514,  0.4761]]), array([ 0.0020]))

In [35]:
skridge = Ridge(alpha=0.1)
skridge.fit(X2, y)
skridge.coef_, skridge.intercept_

(array([[ 0.2120, -0.6555,  0.4732]]), array([ 0.0020]))

In [36]:
myRidge = MyRidge(mu=0.1)
myRidge.fit(X1, y)
myRidge.beta

array([[ 0.2109],
       [-0.6514],
       [ 0.4762]])

In [37]:
myRidge = MyRidge(mu=0.1)
myRidge.fit(X2, y)
myRidge.beta

array([[ 0.2120],
       [-0.6555],
       [ 0.4732]])

## プログラム3.9 リッジ回帰($\mu = 1$)の数値例 (p79)

In [38]:
# パラメータを1に設定します
mu = 1
beta1 = ridge(X1, y, mu)
print(beta1)

# [[ 0.01017256]
# [-0.47145393]
# [ 0.3798 ]]

beta2 = ridge(X2, y, mu)
print(beta2)

# [[ 0.01227368]
# [-0.47396013]
# [ 0.37864896]]

[[ 0.0102]
 [-0.4715]
 [ 0.3798]]
[[ 0.0123]
 [-0.4740]
 [ 0.3786]]


In [39]:
skridge = Ridge(alpha=1)
skridge.fit(X1, y)
skridge.coef_, skridge.intercept_

(array([[ 0.0102, -0.4715,  0.3798]]), array([ 0.0025]))

In [40]:
skridge = Ridge(alpha=1)
skridge.fit(X2, y)
skridge.coef_, skridge.intercept_

(array([[ 0.0123, -0.4740,  0.3786]]), array([ 0.0025]))

In [41]:
myRidge = MyRidge(mu=1)
myRidge.fit(X1, y)
myRidge.beta

array([[ 0.0102],
       [-0.4715],
       [ 0.3798]])

In [42]:
myRidge = MyRidge(mu=1)
myRidge.fit(X2, y)
myRidge.beta

array([[ 0.0123],
       [-0.4740],
       [ 0.3786]])

# 3.12 部分的最小二乗法 (PLS) (p80)

- 多重共線性問題の回避のための次元削減では、相当量の情報量を無駄にしている
- リッジ回帰では、サンプル数が入力変数より少ない場合、回帰計算ができない

<hr>

- 線形回帰では入力変数と出力変数との間での相関関係が重要です
- 入力データの次元を削減する際も、以下が考えられます
    - 入力変数間の相関関係のみならず
    - 入出力間の相関関係も考慮すべき
    
    
    
<div style="text-align:center">
<img src="img/fig3.8.PNG" width="40%" >
</div>

## プログラム3.10 NIPALS によるPLS1（linear_regression.py）(p86)

In [43]:
def nipals_pls1(X, y, R):
    """
    NIPALS アルゴリズムを用いて回帰係数を計算します (PLS1).

    パラメータ
    ----------
    X: 入力データ
    y: 出力データ
    R: 潜在変数の数

    戻り値
    -------
    beta: 回帰係数
    W, P, D: PLS 1 モデルのパラメータ
    T: 潜在変数
    """

    # yをベクトル化します
    y = y.reshape(-1, 1)

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    D = np.zeros((R, 1))
    T = np.zeros((X.shape [0], R))

    # NIPALS を計算します
    for r in range(R):
        # 重みを求めます
        w = (X.T @ y)/ np.linalg.norm(X.T @ y)
        # 潜在変数を計算します
        t = X @ w
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数を求めます
        d =(t.T @ y)/(t.T @ t)
        # デフレーションを行います
        X = X - t.reshape(-1, 1) @ p.T
        y = y - t @ d
        # パラメータを格納します
        W[:,r] = w.T
        P[:,r] = p.T
        D[r] = d.T
        T[:,r] = t.T

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ D
    return beta, W, P, D, T

## *sklearn.cross_decomposition.PLSRegression (SHOWME)

In [44]:
from sklearn.cross_decomposition import PLSRegression

## *MyPLS (numpy from scratch) (TODO)

## プログラム3.11 PLS1 (潜在変数 R = 2) の数値例 (p87)

In [45]:
# 潜在変数が2 のとき
R = 2
# beta1 = nipals_pls1(X1, y, R)
beta1, _, _, _, _  = nipals_pls1(X1, y, R)
print(beta1)

# [[ 0.25850307]
# [-0.68870411]
# [ 0.4939176 ]]


# beta2 = nipals_pls1(X2, y, R)
beta2, _, _, _, _ = nipals_pls1(X2, y, R)
print(beta2)

# [[ 0.25927822]
# [-0.69216413]
# [ 0.49144161]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6922]
 [ 0.4914]]


In [46]:
plsReg = PLSRegression(n_components=2)
plsReg.fit(X1, y)
plsReg.coef_

array([[ 0.2581],
       [-0.6895],
       [ 0.4945]])

In [47]:
plsReg = PLSRegression(n_components=2)
plsReg.fit(X2, y)
plsReg.coef_

array([[ 0.2597],
       [-0.6927],
       [ 0.4919]])

## プログラム3.11 PLS1 (潜在変数 R = 1) の数値例 (p87)

In [48]:
# 潜在変数が1 のとき
R = 1
# beta1 = nipals_pls1(X1, y, R)
beta1, _, _, _, _  = nipals_pls1(X1, y, R)
print(beta1)

# [[-0.23825147]
# [-0.38052552]
# [ 0.36808306]]

# beta2 = nipals_pls1(X2, y, R)
beta2, _, _, _, _  = nipals_pls1(X2, y, R)
print(beta2)

# [[-0.23758087]
# [-0.38091899]
# [ 0.36748303]]

[[-0.2383]
 [-0.3805]
 [ 0.3681]]
[[-0.2376]
 [-0.3809]
 [ 0.3675]]


In [49]:
plsReg = PLSRegression(n_components=1)
plsReg.fit(X1, y)
plsReg.coef_

array([[-0.2388],
       [-0.3806],
       [ 0.3679]])

In [50]:
plsReg = PLSRegression(n_components=1)
plsReg.fit(X2, y)
plsReg.coef_

array([[-0.2377],
       [-0.3813],
       [ 0.3680]])

# 3.13 PLS1モデルの導出　(p82) (TODO)

# 3.15 重回帰モデルへの変換　(p86) (TODO)

# 3.16 出力変数が複数ある場合 (PLS2) (p89)

## プログラム3.12 NIPALS によるPLS2（linear_regression.py） (p93)

In [51]:
# PLS 2 本体の関数
def nipals_pls2(X, Y, R, epsilon=0.01):
    """
    NIPALS アルゴリズムを用いて回帰係数を計算します（PLS2）．

    パラメータ
    ----------
    X: 入力データ
    Y: 出力データ
    R: 潜在変数の数
    epsilon: （デフォルト: 0.01）

    戻り値
    -------
    beta: 回帰係数
    W, P, Q: PLS 2 モデルのパラメータ
    T: 潜在変数
    """

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    Q = np.zeros((Y.shape [1], R))
    T = np.zeros((X.shape [0], R))

    for r in range(R):
        # アルゴリズム2 よりw, c, t を求めます
        w, c, t = calc_parameter(X, Y, epsilon)
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数を求めます
        q =(Y.T @ t)/(t.T @ t)
        # デフレーションを行います
        X = X - np.outer(t, p)
        Y = Y - np.outer(t, q)
        # パラメータを保存します
        W[:,r] = w
        P[:,r] = p
        Q[:,r] = q
        T[:,r] = t

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ Q.T

    return beta, W, P, Q, T


# アルゴリズム2 を計算する関数
def calc_parameter(X, Y, epsilon):
    u = Y[:,0]
    while True :
        # 重みベクトルw を更新します
        w = X.T @ u / np.linalg.norm(X.T @ u)
        # 潜在変数t を更新します
        t = X @ w
        # 重みベクトルc を更新します
        c = Y.T @ t /np.linalg.norm(Y.T @ t)
        # 潜在変数u を更新します
        u_new = Y @ c
        # 収束判定を行います
        if np.linalg.norm(u_new - u) < epsilon: break
        u = u_new
    return w, c, t

## *MyNipals (TODO)

# 3.17 PLSと固有値問題・特異値分解 (p94)(TODO)

## プログラム3.13 SIMPLS によるPLS（linear_regression.py） (p96)

In [52]:
def simpls(X, Y, R):
    """
    SIMPLS アルゴリズムを用いて回帰係数を計算します. 

    パラメータ
    ----------
    X: 入力データ
    Y: 出力データ
    R: 潜在変数の数

    戻り値
    -------
    beta: 回帰係数
    W, P, Q: PLS 1 モデルのパラメータ
    T, U: 潜在変数
    cont: 寄与率
    """
    # yをベクトル化します
    Y = Y.reshape(-1, 1)

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    Q = np.zeros((Y.shape [1], R))
    T = np.zeros((X.shape [0], R))
    U = np.zeros((Y.shape [0], R))
    ssq = np.zeros([R,2])
    ssqX = np.sum(X**2)
    ssqY = np.sum(Y**2)

    for r in range(R):
        # 特異値分をします
        u, s, v = np.linalg.svd(Y.T @ X)
        # 最大特異値に対応する右特異値ベクトルを求めます
        w = v[0,:].T
        # 潜在変数t を求めます
        t = X @ w
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数　q　を求めます
        q =(Y.T @ t)/(t.T @ t)
        # 潜在変数u を求めます
        u = Y @ q
        # デフレーションを行います
        X = X - np.outer(t, p)
        Y = Y - np.outer(t, q)
        ssq [r,0] = np.sum(X**2)/ ssqX
        ssq [r,1] = np.sum(Y**2)/ ssqY
        # パラメータを保存します
        W[:,r] = w.T
        P[:,r] = p.T
        Q[:,r] = q.T
        T[:,r] = t.T
        U[:,r] = u.T

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ Q.T

    # 寄与率を計算します
    cont = np.zeros([R,2])
    cont [0,:] = 1 - ssq [0,:]
    for r in range(1,R):
        cont [r,:] = ssq [r-1,:] - ssq[r,:]

    return beta, W, P, Q, T, U, cont

## *MySimpls (TODO)

## プログラム3.14 SIMPLS の数値例 (p97)

In [53]:
# 潜在変数が2のとき
R = 2

# beta1 = simpls(X1, y, R)
beta1, _, _, _, _, _, _ = simpls(X1, y, R)
print(beta1)
# [[ 0.25850307]
# [-0.68870411]
# [ 0.4939176 ]]

beta2, _, _, _, _, _, _ = simpls(X2, y, R)
print(beta2)
# [[ 0.25927822]
# [-0.69216413]
# [ 0.49144161]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6922]
 [ 0.4914]]


In [54]:
# 潜在変数が1のとき
R = 1
# beta1 = simpls(X1, y, R)
beta1, _, _, _, _, _, _ = simpls(X1, y, R)
print(beta1)
# [[-0.23825147]
# [-0.38052552]
# [ 0.36808306]]

# beta2 = simpls(X2, y, R)
beta2, _, _, _, _, _, _ = simpls(X2, y, R)
print(beta2)
# [[-0.23758087]
# [-0.38091899]
# [ 0.36748303]]

[[-0.2383]
 [-0.3805]
 [ 0.3681]]
[[-0.2376]
 [-0.3809]
 [ 0.3675]]


# 3.18 ハイパーパラメータの調整 (p98) (TODO)

# Last