# Chap 3 回帰分析と最小二乗法


![](https://m.media-amazon.com/images/I/51+dt08QnxL._SY346_.jpg)

In [1]:
U, Sigma, VT = np.linalg.svd(X, full_matrices=False)
U, Sigma, VT

NameError: name 'np' is not defined

In [ ]:
U.shape, Sigma.shape, VT.shape

In [ ]:
U @ np.diag(Sigma) @ VT

# 3.2 最小二乗法

p53 (3.16)

$$
\begin{aligned}
X\beta &= y \\
X^T X \hat{\beta} &= X^T y \\
\hat{\beta} &= (X^T X)^{-1} X^T y
\end{aligned}
$$

<hr>
p56 (3.22)

$$
\begin{aligned}
\hat{y} &= X \hat{\beta} \\
\hat{y} &= X (X^T X)^{-1} X^T y \\
\hat{y} &= P y \ \ \ \ (\because P= X (X^T X)^{-1} X^T \ \ 射影行列 )\\
\end{aligned}
$$

<hr>

p56 (3.23)

$$
\begin{aligned}
P &= X (X^T X)^{-1} X^T \ \\ \\
P^2 &= PP \\
&= (X (X^T X)^{-1} X^T) \ (X (X^T X)^{-1} X^T) \\
&= X \ (X^T X)^{-1} (X^T X ) \ (X^T X)^{-1} \ X^T \\
&= X  (X^T X)^{-1}  X^T \\
&= P \\
\end{aligned}
$$


### プログラム3.2 最小二乗法の数値例 (p54)

In [1]:
import numpy as np
from linear_regression import least_squares , ls_est

np.set_printoptions(formatter={'float':'{: .4f}'.format})

# データを定義します
X = np.array([[0.01, 0.50, -0.12],
			[0.97, -0.63, 0.02],
			[0.41, 1.15, -1.17],
			[-1.38, -1.02, 1.27]])

y = np.array([[0.25], [0.08], [1.03], [-1.37]])
x = np.array([1, 0.7, -0.2])


# 回帰係数を求めます．
beta = least_squares(X, y)
print(beta)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
# 未知サンプルから出力を予測します
y_hat = ls_est(x, beta)
print(y_hat)
# [0.7241999]

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[ 0.7242]


### numpy from scratch (TODO)

### sklearn.linear_model.LinearRegression

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
lr = LinearRegression(fit_intercept=True)

In [4]:
lr.fit(X,y)

LinearRegression()

In [5]:
lr.coef_, lr.intercept_

(array([[ 0.3636,  0.4164, -0.3466]]), array([-0.0034]))

# 3.7 多重共線性の問題

### プログラム3.3 多重共線性がないデータの場合 (p65)

In [6]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[0.01, 0.50, -0.12],
                [0.97, -0.63, 0.02],
                [0.41, 1.15, -1.17],
                [-1.38, -1.02, 1.27]])
X2 = np.array( [[-0.01, 0.52, -0.12],
                [0.96, -0.64, 0.03],
                [0.43, 1.14, -1.17],
                [-1.38, -1.01, 1.27]])

y = np.array ([[0.25], [0.08], [1.03], [-1.37]])


# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
beta2 = least_squares(X2, y)
print(beta2)
# [[ 0.37270979]
# [ 0.41379869]
# [-0.34252764]]
print(X1 - X2)

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[[ 0.3727]
 [ 0.4138]
 [-0.3425]]
[[ 0.0200 -0.0200  0.0000]
 [ 0.0100  0.0100 -0.0100]
 [-0.0200  0.0100  0.0000]
 [ 0.0000 -0.0100  0.0000]]


#### 行列の条件数 $\kappa(A)$

In [7]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2),

(135.75293858717927, 133.39346575985206)

### sklearn.linear_model.LinearRegression

In [8]:
lr = LinearRegression()
lr.fit(X1, y)
lr.coef_, lr.intercept_

(array([[ 0.3636,  0.4164, -0.3466]]), array([-0.0034]))

In [9]:
lr = LinearRegression()
lr.fit(X2, y)
lr.coef_, lr.intercept_

(array([[ 0.3729,  0.4142, -0.3420]]), array([-0.0027]))

### プログラム3.4 多重共線性があるデータの場合 (p67)

In [10]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array([0.4, 1.17, -1.14, -0.42])

# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[0.54496962]
# [0.24094799]
# [1.64044474]]

beta2 = least_squares(X2, y)
print(beta2)
# [[-0.42794288]
# [-2.86298696]
# [-2.2029719 ]]

[[ 0.5450]
 [ 0.2409]
 [ 1.6404]]
[[-0.4279]
 [-2.8630]
 [-2.2030]]


In [11]:
X1 - X2

array([[ 0.0000,  0.0000, -0.0100],
       [ 0.0000,  0.0000,  0.0100],
       [ 0.0100,  0.0000,  0.0000],
       [-0.0100,  0.0000,  0.0000]])

#### 行列の条件数 $\kappa(A)$

In [12]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2),

(235456.75658580603, 470649.97301951883)

# 3.8 サンプル数が入力変数の数よりも少ない場合

- 方程式の数より未知数が多いのだから、普通の方程式では解けるはずがない

$$
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\
x_{21} & x_{22} & x_{23}
\end{bmatrix}
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\end{bmatrix} =
\begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
\end{bmatrix}
$$

- 一方、よく見る最小二乗法の問題では、未知数より方程式の和の方が多い、やはり、普通の方程式の解き方とは違う

$$
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\
x_{23} & x_{22} & x_{23} \\
x_{31} & x_{32} & x_{33} \\
x_{41} & x_{42} & x_{43} \\
x_{51} & x_{52} & x_{53} \\
x_{61} & x_{67} & x_{63} \\
x_{71} & x_{72} & x_{73} \\
x_{81} & x_{82} & x_{83} \\
x_{91} & x_{92} & x_{93}
\end{bmatrix}
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\end{bmatrix} =
\begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
\end{bmatrix}
$$

# 3.9 擬似逆行列を用いる方法

- $AA^+A = A$
- $A^+AA^+ = A$
- $(AA^+)^T = AA^+$
- $(A^+A)^T = A^+A$


$$
\beta^* = (X^T X)^+ X^T y
$$

In [13]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_ = np.linalg.pinv(A)
A_

array([[-0.9444,  0.4444],
       [-0.1111,  0.1111],
       [ 0.7222, -0.2222]])

In [14]:
# A A+ A = A
A @ A_ @ A

array([[ 1.0000,  2.0000,  3.0000],
       [ 4.0000,  5.0000,  6.0000]])

In [15]:
# A+ A A+ = A+
A_ @ A @ A_

array([[-0.9444,  0.4444],
       [-0.1111,  0.1111],
       [ 0.7222, -0.2222]])

In [16]:
# (A A+).T = A A+
(A @ A_).T

array([[ 1.0000,  0.0000],
       [ 0.0000,  1.0000]])

In [17]:
# (A+ A).T = A+ A
(A_ @ A).T

array([[ 0.8333,  0.3333, -0.1667],
       [ 0.3333,  0.3333,  0.3333],
       [-0.1667,  0.3333,  0.8333]])

In [18]:
A_ @ A

array([[ 0.8333,  0.3333, -0.1667],
       [ 0.3333,  0.3333,  0.3333],
       [-0.1667,  0.3333,  0.8333]])

In [19]:
b = np.array([[3],
             [6]])

In [20]:
beta = np.linalg.pinv(A.T @ A) @ A.T @ b
beta

array([[-0.1667],
       [ 0.3333],
       [ 0.8333]])

In [21]:
A = np.array([[1, 2]])

b = np.array([[2]])

A_ = np.linalg.pinv(A)
A_

array([[ 0.2000],
       [ 0.4000]])

In [22]:
beta = np.linalg.pinv(A.T @ A) @ A.T @ b
beta

array([[ 0.4000],
       [ 0.8000]])

# 3.10 主成分回帰 (PCR) (p72)

- [Principal Component Regression vs Partial Least Squares Regression](https://scikit-learn.org/stable/auto_examples/cross_decomposition/plot_pcr_vs_pls.html)

### プログラム3.5 RCR（linear_regression.py） (p73)

In [10]:
import numpy as np
from linear_regression import least_squares
from pca import pca

def pcr(X, y, R):
    """
    PCR を用いて回帰係数を計算します．ラメータ
    ----------
    X: 入力データ
    y: 出力データ
    R: 主成分の数
    戻り値
    -------
    beta: 回帰係数
    """
    # yをベクトル化します
    y = y.reshape(-1, 1)
    # 主成分分析を行います
    P, T = pca(X)
    # R番目までの主成分得点行列を取り出します
    T = T[:,:R]
    # 最小二乗法により回帰係数を求めます
    beta_R = least_squares(T, y)
    beta = P[:,:R] @ beta_R
    return beta

### プログラム3.6 主成分数を2 とした場合 (p74)

In [11]:
# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array ([[0.4], [1.17], [-1.14], [-0.42]])

#主成分数を2に設定します
R = 2
beta1 = pcr(X1, y, R)
print(beta1)
# [[ 0.25849154]
# [-0.68874152]
# [ 0.49387146]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[ 0.25929082]
# [-0.69212429]
# [ 0.49149105]]

[[ 0.25849154]
 [-0.68874152]
 [ 0.49387146]]
[[ 0.25929082]
 [-0.69212429]
 [ 0.49149105]]


### プログラム3.7 主成分数を1 とした場合 (p75)

In [12]:
# 主成分数を1 に設定します
R = 1
beta1 = pcr(X1, y, R)
print(beta1)
# [[-0.30313539]
# [-0.32858522]
# [ 0.34217102]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[-0.30335458]
# [-0.32755389]
# [ 0.34127419]]

[[-0.30313539]
 [-0.32858522]
 [ 0.34217102]]
[[-0.30335458]
 [-0.32755389]
 [ 0.34127419]]


### MyPCR (from scratch)

In [16]:
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

class MyPCR(TransformerMixin, BaseEstimator):
    def __init__(self, n_components):
        self.n_components = n_components
        self.pca = PCA(n_components=n_components)
        self.regression = LinearRegression()
    def fit(self, X, y=None):
        self.pca.fit(X)
        X_reduced = self.pca.transform(X)
        X_returned = self.pca.inverse_transform(X_reduced)
        self.regression.fit(X_returned,y)
        self.coef_ = self.regression.coef_
        self.intercept_ = self.regression.intercept_
        return self
    def predict(self, X):
        X_reduced = self.pca.transform(X)
        X_returned = self.pca.inverse_transform(X_reduced)
        return self.regression.predict(X_returned)

In [17]:
# データを定義します
X1 = np.array([[-1.12, -0.51, 0.69],
			[-0.43, -1.12, 1.02],
			[0.37, 1.10, -0.98],
			[1.19, 0.53, -0.73]])

X2 = np.array([[-1.12, -0.51, 0.70],
			[-0.43, -1.12, 1.01],
			[0.36, 1.10, -0.98],
			[1.20, 0.53, -0.73]])

y = np.array([0.4, 1.17, -1.14, -0.42])#.reshape(-1.1)
y = y.reshape(-1,1)

In [18]:
pcr = MyPCR(n_components=2)
pcr.fit(X1,y)
pcr.coef_

array([[ 0.25847827, -0.68873417,  0.49386882]])

In [19]:
pcr = MyPCR(n_components=2)
pcr.fit(X2,y)
pcr.coef_

array([[ 0.25927779, -0.69211701,  0.49148851]])

## 3.11 リッジ回帰

### プログラム3.8 リッジ回帰（linear_regression） (p77)

In [20]:
def ridge(X, y, mu=0.1):
    """
    リッジ回帰を用いて回帰係数を計算します. 

    パラメータ
    ----------
    X: 入力データ
    y: 出力データ
    mu: パラメータ(デフォルト: 0.1)

    戻り値
    -------
    beta_ridge: 回帰係数
    """
    # yをベクトル化します
    y = y.reshape(-1, 1)

    # リッジ回帰の回帰係数を求めます
    I = np.eye(X.shape [1])
    beta_ridge = np.linalg.inv(X.T @ X + mu * I)@ X.T @ y
    return beta_ridge

### プログラム3.9 リッジ回帰の数値例 (p79)

In [21]:
# パラメータを0.1に設定します
mu = 0.1
beta1 = ridge(X1, y, mu)
print(beta1)
# [[ 0.21088992]
# [-0.65139114]
# [ 0.47615414]]
beta2 = ridge(X2, y, mu)
print(beta2)

# [[ 0.21198147]
# [-0.65545325]
# [ 0.47322964]]

[[ 0.21088992]
 [-0.65139114]
 [ 0.47615414]]
[[ 0.21198147]
 [-0.65545325]
 [ 0.47322964]]


In [22]:
# パラメータを1に設定します
mu = 1
beta1 = ridge(X1, y, mu)
print(beta1)

# [[ 0.01017256]
# [-0.47145393]
# [ 0.3798 ]]

beta2 = ridge(X2, y, mu)
print(beta2)

# [[ 0.01227368]
# [-0.47396013]
# [ 0.37864896]]

[[ 0.01017256]
 [-0.47145393]
 [ 0.3798    ]]
[[ 0.01227368]
 [-0.47396013]
 [ 0.37864896]]


### sklearn.linear_model.Ridge

In [23]:
from sklearn.linear_model import Ridge

In [24]:
ridge = Ridge(alpha=0.1)
ridge.fit(X1, y)
ridge.coef_, ridge.intercept_

(array([[ 0.21086988, -0.65140733,  0.476123  ]]), array([0.00197283]))

In [25]:
ridge = Ridge(alpha=0.1)
ridge.fit(X2, y)
ridge.coef_, ridge.intercept_

(array([[ 0.21196132, -0.65546988,  0.47319793]]), array([0.0019701]))

In [26]:
ridge = Ridge(alpha=1)
ridge.fit(X1, y)
ridge.coef_, ridge.intercept_

(array([[ 0.01016249, -0.47145234,  0.37979504]]), array([0.00247459]))

In [27]:
ridge = Ridge(alpha=1)
ridge.fit(X2, y)
ridge.coef_

array([[ 0.01226369, -0.4739586 ,  0.37864398]])

### MyRidge (from scratch) TODO

$$
\beta_{ridge} = (X^T X + \mu I)^{-1} X^T y \tag{3.91}
$$

In [44]:
import numpy as np
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.decomposition import PCA

class MyRidge(TransformerMixin, BaseEstimator):
    def __init__(self, mu=0.1):
        self.mu = mu
        self.beta = None
        
    def fit(self, X, y):
        m, n = X.shape
        self.beta = np.linalg.inv(X.T @ X + mu*np.eye(n)) @ X.T @ y
        return self
    def predict(self, X):
        return X @self.beta

In [49]:
ridge = MyRidge(mu=1)

In [50]:
ridge.fit(X1, y)

MyRidge(mu=1)

In [51]:
ridge.beta

array([[ 0.01017256],
       [-0.47145393],
       [ 0.3798    ]])

## 3.12 部分的最小二乗法 (PLS)

### プログラム3.10 NIPALS によるPLS1（linear_regression.py）(p86)

In [40]:
def nipals_pls1(X, y, R):
    """
    NIPALS アルゴリズムを用いて回帰係数を計算します (PLS1).

    パラメータ
    ----------
    X: 入力データ
    y: 出力データ
    R: 潜在変数の数

    戻り値
    -------
    beta: 回帰係数
    W, P, D: PLS 1 モデルのパラメータ
    T: 潜在変数
    """

    # yをベクトル化します
    y = y.reshape(-1, 1)

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    D = np.zeros((R, 1))
    T = np.zeros((X.shape [0], R))

    # NIPALS を計算します
    for r in range(R):
        # 重みを求めます
        w = (X.T @ y)/ np.linalg.norm(X.T @ y)
        # 潜在変数を計算します
        t = X @ w
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数を求めます
        d =(t.T @ y)/(t.T @ t)
        # デフレーションを行います
        X = X - t.reshape(-1, 1) @ p.T
        y = y - t @ d
        # パラメータを格納します
        W[:,r] = w.T
        P[:,r] = p.T
        D[r] = d.T
        T[:,r] = t.T

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ D
    return beta, W, P, D, T

### プログラム3.11 PLS1 の数値例 (p87)

In [41]:
# 潜在変数が2 のとき
R = 2
# beta1 = nipals_pls1(X1, y, R)
beta1, _, _, _, _  = nipals_pls1(X1, y, R)
print(beta1)

# [[ 0.25850307]
# [-0.68870411]
# [ 0.4939176 ]]


# beta2 = nipals_pls1(X2, y, R)
beta2, _, _, _, _ = nipals_pls1(X2, y, R)
print(beta2)

# [[ 0.25927822]
# [-0.69216413]
# [ 0.49144161]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6922]
 [ 0.4914]]


In [42]:
# 潜在変数が1 のとき
R = 1
# beta1 = nipals_pls1(X1, y, R)
beta1, _, _, _, _  = nipals_pls1(X1, y, R)
print(beta1)

# [[-0.23825147]
# [-0.38052552]
# [ 0.36808306]]

# beta2 = nipals_pls1(X2, y, R)
beta2, _, _, _, _  = nipals_pls1(X2, y, R)
print(beta2)

# [[-0.23758087]
# [-0.38091899]
# [ 0.36748303]]

[[-0.2383]
 [-0.3805]
 [ 0.3681]]
[[-0.2376]
 [-0.3809]
 [ 0.3675]]


### sklearn.cross_decomposition.PLSRegression (SHOWME)

In [43]:
from sklearn.cross_decomposition import PLSRegression

In [44]:
pls = PLSRegression(n_components=1)
pls.fit(X1, y)
pls.coef_

array([[-0.2388],
       [-0.3806],
       [ 0.3679]])

In [45]:
pls = PLSRegression(n_components=1)
pls.fit(X2, y)
pls.coef_

array([[-0.2377],
       [-0.3813],
       [ 0.3680]])

In [46]:
pls = PLSRegression(n_components=1)
pls.fit(X1, y)
pls.coef_

array([[-0.2388],
       [-0.3806],
       [ 0.3679]])

In [47]:
pls = PLSRegression(n_components=1)
pls.fit(X2, y)
pls.coef_

array([[-0.2377],
       [-0.3813],
       [ 0.3680]])

# 3.16 出力変数が複数ある場合 (PLS2) (p89)

### プログラム3.12 NIPALS によるPLS2（linear_regression.py） (p93)

In [48]:
# PLS 2 本体の関数
def nipals_pls2(X, Y, R, epsilon=0.01):
    """
    NIPALS アルゴリズムを用いて回帰係数を計算します（PLS2）．

    パラメータ
    ----------
    X: 入力データ
    Y: 出力データ
    R: 潜在変数の数
    epsilon: （デフォルト: 0.01）

    戻り値
    -------
    beta: 回帰係数
    W, P, Q: PLS 2 モデルのパラメータ
    T: 潜在変数
    """

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    Q = np.zeros((Y.shape [1], R))
    T = np.zeros((X.shape [0], R))

    for r in range(R):
        # アルゴリズム2 よりw, c, t を求めます
        w, c, t = calc_parameter(X, Y, epsilon)
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数を求めます
        q =(Y.T @ t)/(t.T @ t)
        # デフレーションを行います
        X = X - np.outer(t, p)
        Y = Y - np.outer(t, q)
        # パラメータを保存します
        W[:,r] = w
        P[:,r] = p
        Q[:,r] = q
        T[:,r] = t

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ Q.T

    return beta, W, P, Q, T


# アルゴリズム2 を計算する関数
def calc_parameter(X, Y, epsilon):
    u = Y[:,0]
    while True :
        # 重みベクトルw を更新します
        w = X.T @ u / np.linalg.norm(X.T @ u)
        # 潜在変数t を更新します
        t = X @ w
        # 重みベクトルc を更新します
        c = Y.T @ t /np.linalg.norm(Y.T @ t)
        # 潜在変数u を更新します
        u_new = Y @ c
        # 収束判定を行います
        if np.linalg.norm(u_new - u) < epsilon: break
        u = u_new
    return w, c, t

### プログラム3.13 SIMPLS によるPLS（linear_regression.py） (p96)

In [49]:
def simpls(X, Y, R):
    """
    SIMPLS アルゴリズムを用いて回帰係数を計算します. 

    パラメータ
    ----------
    X: 入力データ
    Y: 出力データ
    R: 潜在変数の数

    戻り値
    -------
    beta: 回帰係数
    W, P, Q: PLS 1 モデルのパラメータ
    T, U: 潜在変数
    cont: 寄与率
    """
    # yをベクトル化します
    Y = Y.reshape(-1, 1)

    # パラメータを保存する変数を作成します
    W = np.zeros((X.shape [1], R))
    P = np.zeros((X.shape [1], R))
    Q = np.zeros((Y.shape [1], R))
    T = np.zeros((X.shape [0], R))
    U = np.zeros((Y.shape [0], R))
    ssq = np.zeros([R,2])
    ssqX = np.sum(X**2)
    ssqY = np.sum(Y**2)

    for r in range(R):
        # 特異値分をします
        u, s, v = np.linalg.svd(Y.T @ X)
        # 最大特異値に対応する右特異値ベクトルを求めます
        w = v[0,:].T
        # 潜在変数t を求めます
        t = X @ w
        # ローディングベクトルを求めます
        p =(X.T @ t)/(t.T @ t)
        # 回帰係数　q　を求めます
        q =(Y.T @ t)/(t.T @ t)
        # 潜在変数u を求めます
        u = Y @ q
        # デフレーションを行います
        X = X - np.outer(t, p)
        Y = Y - np.outer(t, q)
        ssq [r,0] = np.sum(X**2)/ ssqX
        ssq [r,1] = np.sum(Y**2)/ ssqY
        # パラメータを保存します
        W[:,r] = w.T
        P[:,r] = p.T
        Q[:,r] = q.T
        T[:,r] = t.T
        U[:,r] = u.T

    # 回帰係数を計算します
    beta = W @ np.linalg.inv(P.T @ W)@ Q.T

    # 寄与率を計算します
    cont = np.zeros([R,2])
    cont [0,:] = 1 - ssq [0,:]
    for r in range(1,R):
        cont [r,:] = ssq [r-1,:] - ssq[r,:]

    return beta, W, P, Q, T, U, cont

### プログラム3.14 SIMPLS の数値例 (p97)

In [50]:
# 潜在変数が2のとき
R = 2

# beta1 = simpls(X1, y, R)
beta1, _, _, _, _, _, _ = simpls(X1, y, R)
print(beta1)
# [[ 0.25850307]
# [-0.68870411]
# [ 0.4939176 ]]

beta2, _, _, _, _, _, _ = simpls(X2, y, R)
print(beta2)
# [[ 0.25927822]
# [-0.69216413]
# [ 0.49144161]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6922]
 [ 0.4914]]


In [51]:
# 潜在変数が1のとき
R = 1
# beta1 = simpls(X1, y, R)
beta1, _, _, _, _, _, _ = simpls(X1, y, R)
print(beta1)
# [[-0.23825147]
# [-0.38052552]
# [ 0.36808306]]

# beta2 = simpls(X2, y, R)
beta2, _, _, _, _, _, _ = simpls(X2, y, R)
print(beta2)
# [[-0.23758087]
# [-0.38091899]
# [ 0.36748303]]

[[-0.2383]
 [-0.3805]
 [ 0.3681]]
[[-0.2376]
 [-0.3809]
 [ 0.3675]]


# 3.18 ハイパーパラメータの調整

## SImpls

In [52]:
pls = PLSRegression(n_components=2)
pls.fit(X1, y)
pls.coef_

array([[ 0.2581],
       [-0.6895],
       [ 0.4945]])

# Last

In [53]:
import numpy as np

In [54]:
N = 1_000_000
total = 0
for i in range(1,N):
    total += 6/i**2
    
np.sqrt(total)

3.14159169865946

In [55]:
np.pi

3.141592653589793