# Chap 3 回帰分析と最小二乗法


![](https://m.media-amazon.com/images/I/51+dt08QnxL._SY346_.jpg)

In [1]:
U, Sigma, VT = np.linalg.svd(X, full_matrices=False)
U, Sigma, VT

NameError: name 'np' is not defined

In [2]:
U.shape, Sigma.shape, VT.shape

NameError: name 'U' is not defined

In [22]:
U @ np.diag(Sigma) @ VT

array([[ 2.,  2.],
       [ 1., -1.],
       [-1.,  1.],
       [-2., -2.]])

# 3.2 最小二乗法

p53 (3.16)

$$
\begin{aligned}
X\beta &= y \\
X^T X \hat{\beta} &= X^T y \\
\hat{\beta} &= (X^T X)^{-1} X^T y
\end{aligned}
$$

<hr>
p56 (3.22)

$$
\begin{aligned}
\hat{y} &= X \hat{\beta} \\
\hat{y} &= X (X^T X)^{-1} X^T y \\
\hat{y} &= P y \ \ \ \ (\because P= X (X^T X)^{-1} X^T \ \ 射影行列 )\\
\end{aligned}
$$

<hr>

p56 (3.23)

$$
\begin{aligned}
P &= X (X^T X)^{-1} X^T \ \\ \\
P^2 &= PP \\
&= (X (X^T X)^{-1} X^T) \ (X (X^T X)^{-1} X^T) \\
&= X \ (X^T X)^{-1} (X^T X ) \ (X^T X)^{-1} \ X^T \\
&= X  (X^T X)^{-1}  X^T \\
&= P \\
\end{aligned}
$$


### プログラム3.2 最小二乗法の数値例 (p54)

In [22]:
import numpy as np
from linear_regression import least_squares , ls_est

np.set_printoptions(formatter={'float':'{: .4f}'.format})

# データを定義します
X = np.array([[0.01, 0.50, -0.12],
			[0.97, -0.63, 0.02],
			[0.41, 1.15, -1.17],
			[-1.38, -1.02, 1.27]])

y = np.array([[0.25], [0.08], [1.03], [-1.37]])
x = np.array([1, 0.7, -0.2])


# 回帰係数を求めます．
beta = least_squares(X, y)
print(beta)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
# 未知サンプルから出力を予測します
y_hat = ls_est(x, beta)
print(y_hat)
# [0.7241999]

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[ 0.7242]


### sklearn.linear_model.LinearRegression

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
lr = LinearRegression(fit_intercept=True)

In [19]:
lr.fit(X1,y)

LinearRegression()

In [20]:
lr.coef_, lr.intercept_

(array([[ 0.3636,  0.4164, -0.3466]]), array([-0.0034]))

In [21]:
lr.fit(X2, y)
lr.coef_, lr.intercept_

(array([[ 0.3729,  0.4142, -0.3420]]), array([-0.0027]))

# 3.7 多重共線性の問題

### プログラム3.3 多重共線性がないデータの場合 (p65)

In [44]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[0.01, 0.50, -0.12],
                [0.97, -0.63, 0.02],
                [0.41, 1.15, -1.17],
                [-1.38, -1.02, 1.27]])
X2 = np.array( [[-0.01, 0.52, -0.12],
                [0.96, -0.64, 0.03],
                [0.43, 1.14, -1.17],
                [-1.38, -1.01, 1.27]])

y = np.array ([[0.25], [0.08], [1.03], [-1.37]])


# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[ 0.36347065]
# [ 0.41624871]
# [-0.34677593]]
beta2 = least_squares(X2, y)
print(beta2)
# [[ 0.37270979]
# [ 0.41379869]
# [-0.34252764]]
print(X1 - X2)

[[ 0.3635]
 [ 0.4162]
 [-0.3468]]
[[ 0.3727]
 [ 0.4138]
 [-0.3425]]
[[ 0.0200 -0.0200  0.0000]
 [ 0.0100  0.0100 -0.0100]
 [-0.0200  0.0100  0.0000]
 [ 0.0000 -0.0100  0.0000]]


#### 行列の条件数 $\kappa(A)$

In [45]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2),

(135.75293858717927, 133.39346575985206)

### sklearn.linear_model.LinearRegression

In [46]:
lr = LinearRegression()
lr.fit(X1, y)
lr.coef_, lr.intercept_

(array([[ 0.3636,  0.4164, -0.3466]]), array([-0.0034]))

In [47]:
lr = LinearRegression()
lr.fit(X2, y)
lr.coef_, lr.intercept_

(array([[ 0.3729,  0.4142, -0.3420]]), array([-0.0027]))

### プログラム3.4 多重共線性があるデータの場合 (p67)

In [48]:
import numpy as np
from linear_regression import least_squares

# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array([0.4, 1.17, -1.14, -0.42])

# X1，X2それぞれでの回帰係数を計算します
beta1 = least_squares(X1, y)
print(beta1)
# [[0.54496962]
# [0.24094799]
# [1.64044474]]

beta2 = least_squares(X2, y)
print(beta2)
# [[-0.42794288]
# [-2.86298696]
# [-2.2029719 ]]

[[ 0.5450]
 [ 0.2409]
 [ 1.6404]]
[[-0.4279]
 [-2.8630]
 [-2.2030]]


In [49]:
X1 - X2

array([[ 0.0000,  0.0000, -0.0100],
       [ 0.0000,  0.0000,  0.0100],
       [ 0.0100,  0.0000,  0.0000],
       [-0.0100,  0.0000,  0.0000]])

#### 行列の条件数 $\kappa(A)$

In [50]:
np.linalg.cond(X1.T@X1), np.linalg.cond(X2.T@X2),

(235456.75658580603, 470649.97301951883)

# 3.9 擬似逆行列を用いる方法 (TODO)

In [60]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [63]:
A_ = np.linalg.pinv(A.T@A)
A_

array([[ 1.0895,  0.1543, -0.7809],
       [ 0.1543,  0.0247, -0.1049],
       [-0.7809, -0.1049,  0.5710]])

# 3.10 主成分回帰 (PCR) (p72)

- [Principal Component Regression vs Partial Least Squares Regression](https://scikit-learn.org/stable/auto_examples/cross_decomposition/plot_pcr_vs_pls.html)

### プログラム3.5 RCR（linear_regression.py） (p73)

In [71]:
import numpy as np
from linear_regression import least_squares
from pca import pca

def pcr(X, y, R):
    """
    PCR を用いて回帰係数を計算します．ラメータ
    ----------
    X: 入力データ
    y: 出力データ
    R: 主成分の数
    戻り値
    -------
    beta: 回帰係数
    """
    # yをベクトル化します
    y = y.reshape(-1, 1)
    # 主成分分析を行います
    P, T = pca(X)
    # R番目までの主成分得点行列を取り出します
    T = T[:,:R]
    # 最小二乗法により回帰係数を求めます
    beta_R = least_squares(T, y)
    beta = P[:,:R] @ beta_R
    return beta

### プログラム3.6 主成分数を2 とした場合 (p74)

In [72]:
# データを定義します
X1 = np.array( [[-1.12, -0.51, 0.69],
                [-0.43, -1.12, 1.02],
                [0.37, 1.10, -0.98],
                [1.19, 0.53, -0.73]])

X2 = np.array( [[-1.12, -0.51, 0.70],
                [-0.43, -1.12, 1.01],
                [0.36, 1.10, -0.98],
                [1.20, 0.53, -0.73]])

y = np.array ([[0.4], [1.17], [-1.14], [-0.42]])

#主成分数を2に設定します
R = 2
beta1 = pcr(X1, y, R)
print(beta1)
# [[ 0.25849154]
# [-0.68874152]
# [ 0.49387146]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[ 0.25929082]
# [-0.69212429]
# [ 0.49149105]]

[[ 0.2585]
 [-0.6887]
 [ 0.4939]]
[[ 0.2593]
 [-0.6921]
 [ 0.4915]]


### プログラム3.7 主成分数を1 とした場合 (p75)

In [73]:
# 主成分数を1 に設定します
R = 1
beta1 = pcr(X1, y, R)
print(beta1)
# [[-0.30313539]
# [-0.32858522]
# [ 0.34217102]]
beta2 = pcr(X2, y, R)
print(beta2)
# [[-0.30335458]
# [-0.32755389]
# [ 0.34127419]]

[[-0.3031]
 [-0.3286]
 [ 0.3422]]
[[-0.3034]
 [-0.3276]
 [ 0.3413]]


### MyPCR

In [81]:
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.decomposition import PCA

class MyPCR(TransformerMixin, BaseEstimator):
    def __init__(self, n_components):
        self.n_components = n_components
        self.pca = PCA(n_components=n_components)
        self.regression = LinearRegression()
    def fit(self, X, y=None):
        self.pca.fit(X)
        X_reduced = self.pca.transform(X)
        X_returned = self.pca.inverse_transform(X_reduced)
        self.regression.fit(X_returned,y)
        self.coef_ = self.regression.coef_
        self.intercept_ = self.regression.intercept_
        return self
    def predict(self, X):
        X_reduced = self.pca.transform(X)
        X_returned = self.pca.inverse_transform(X_reduced)
        return self.regression.predict(X_returned)

In [82]:
# データを定義します
X1 = np.array([[-1.12, -0.51, 0.69],
			[-0.43, -1.12, 1.02],
			[0.37, 1.10, -0.98],
			[1.19, 0.53, -0.73]])

X2 = np.array([[-1.12, -0.51, 0.70],
			[-0.43, -1.12, 1.01],
			[0.36, 1.10, -0.98],
			[1.20, 0.53, -0.73]])

y = np.array([0.4, 1.17, -1.14, -0.42])#.reshape(-1.1)
y = y.reshape(-1,1)

In [83]:
pcr = MyPCR(n_components=2)
pcr.fit(X1,y)
pcr.coef_

array([[ 0.2585, -0.6887,  0.4939]])

In [85]:
pcr = MyPCR(n_components=2)
pcr.fit(X2,y)
pcr.coef_

array([[ 0.2593, -0.6921,  0.4915]])

In [37]:
pcr = PCR(n_components=1)
pcr.fit(X1,y)
pcr.coef_

array([[-0.30313657, -0.3285865 ,  0.34217235]])

In [38]:
pcr = PCR(n_components=1)
pcr.fit(X2,y)
pcr.coef_

array([[-0.30335576, -0.32755517,  0.34127552]])

## 3.11 リッジ回帰

In [39]:
from sklearn.linear_model import Ridge

In [40]:
ridge = Ridge(alpha=0.1)
ridge.fit(X1, y)
ridge.coef_

array([[ 0.21086988, -0.65140733,  0.476123  ]])

In [41]:
ridge = Ridge(alpha=0.1)
ridge.fit(X2, y)
ridge.coef_

array([[ 0.21196132, -0.65546988,  0.47319793]])

In [42]:
ridge = Ridge(alpha=1)
ridge.fit(X1, y)
ridge.coef_

array([[ 0.01016249, -0.47145234,  0.37979504]])

In [43]:
ridge = Ridge(alpha=1)
ridge.fit(X2, y)
ridge.coef_

array([[ 0.01226369, -0.4739586 ,  0.37864398]])

## 部分的最小二乗法 (PLS)

In [44]:
from sklearn.cross_decomposition import PLSRegression

In [45]:
pls = PLSRegression(n_components=2)
pls.fit(X1, y)
pls.coef_

array([[ 0.2580916 ],
       [-0.6895284 ],
       [ 0.49445928]])

In [46]:
pls = PLSRegression(n_components=2)
pls.fit(X2, y)
pls.coef_

array([[ 0.25968446],
       [-0.69266567],
       [ 0.49185871]])

In [47]:
pls = PLSRegression(n_components=1)
pls.fit(X1, y)
pls.coef_

array([[-0.23884676],
       [-0.38063732],
       [ 0.36792198]])

In [48]:
pls = PLSRegression(n_components=1)
pls.fit(X2, y)
pls.coef_

array([[-0.23767287],
       [-0.38128164],
       [ 0.36795534]])

## SImpls

In [49]:
pls = PLSRegression(n_components=2)
pls.fit(X1, y)
pls.coef_

array([[ 0.2580916 ],
       [-0.6895284 ],
       [ 0.49445928]])

# Last

In [50]:
import numpy as np

In [51]:
N = 1_000_000
total = 0
for i in range(1,N):
    total += 6/i**2
    
np.sqrt(total)

3.14159169865946

In [52]:
np.pi

3.141592653589793